# training mode
TRAINING_MODE_PRE_TRAIN = 'pre_train'
TRAINING_MODE_FINE_TUNE = 'fine_tune'

# pre-training task names
TASK_MASK_SPAN_PREDICTION = 'msp'
TASK_IDENTIFIER_TAGGING = 'it'
TASK_MASK_IDENTIFER_PREDICTION = 'mip'
TASK_BIMODAL_DUAL_GENERATION = 'bdg'

PRE_TRAIN_TASKS = [
    TASK_MASK_SPAN_PREDICTION,
    TASK_IDENTIFIER_TAGGING,
    TASK_MASK_IDENTIFER_PREDICTION,
    TASK_BIMODAL_DUAL_GENERATION
]

LANG_PYTHON = 'python'

MODEL_MODE_CLS = 'identifier_cls'
MODEL_MODE_GEN = 'generation'
